## Example 1

In [ ]:
import tensorflow as tf

In [4]:
# y = mx + b
m = tf.constant(3.0, name='m')
b = tf.constant(1.5, name='b')
x = tf.placeholder(dtype='float32', name='x')

In [5]:
y = m*x + b

In [6]:
sess = tf.Session()

In [7]:
y.eval({x: 2}, session=sess)

7.5

## Example 2
Basic matrix arithmetic

In [8]:
M = tf.constant([[1,2], [3,4]], dtype='float32')

In [11]:
v = tf.constant([5,2], dtype='float32')

In [12]:
sess.run(M+v)

array([[6., 4.],
       [8., 6.]], dtype=float32)

In [13]:
#Element wise multiplication
sess.run(M*v)

array([[ 5.,  4.],
       [15.,  8.]], dtype=float32)

## Example 3
Matrix multiplication

In [15]:
sess.run(tf.matmul(M, tf.reshape(v, [2,1])))

array([[ 9.],
       [23.]], dtype=float32)